# Generated by Django 5.1 on 2024-09-09 11:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_chats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chat',
            name='rechats',
            field=models.ManyToManyField(blank=True, related_name='rechats', to=settings.AUTH_USER_MODEL),
        ),
    ]
