# Generated by Django 5.1.1 on 2024-09-12 09:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0002_alter_chat_likes_alter_chat_rechats'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reply',
            new_name='Rechat',
        ),
    ]
